[build]
command = "yarn build"
publish = "_site"

[dev]
command = "yarn serve"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/images", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[[edge_functions]]
function = "eleventy-edge"
path = "/"
