og:
  locale: en_US
  type: website
  img: headshots/mia-smashing.jpg
styles:
  - title: spec
    url: layer/spec.css
    alt: spec
  - title: browser
  - title: reset
    url: layer/reset.css
    layer: reset
  - title: default
    url: layer/default.css
    layer: default
  - title: features
    url: layer/features.css
    layer: features
  - title: layout
    url: layer/layout.css
    layer: layout
  - title: theme
    url: layer/theme.css
    layer: theme
scripts:
  - scripts.js
theme:
  light: 'hotpink'
  dark: 'mediumvioletred'
preload:
  - as: font
    type: font/woff2
    url: /fonts/alegreya-latin-variable-wghtOnly-normal.woff2
  - as: font
    type: font/woff2
    url: /fonts/alegreya-latin-variable-wghtOnly-italic.woff2
