url: https://www.miriamsuzanne.com/
source:
  repo: https://github.com/mirisuzanne/mia/
  branch: tree/main/
author: &author Miriam Eric Suzanne
title: *author
description: Art, writing, and code from Miriam Suzanne
email: miriam@miriamsuzanne.com
images: /images/
icon: icons/miriam.svg
