url: https://www.miriamsuzanne.com/
source:
  repo: https://github.com/mirisuzanne/mia/
  branch: tree/main/
author: &author Miriam Eric Suzanne
title: *author
description: Art, writing, and code from Miriam Suzanne
email: miriam@miriamsuzanne.com
images: /images/
icon: icons/miriam.svg
nav:
  home: /
  about: /who/
  tags: /tags/
  contact: /contact/
  rss: /feed.xml
og:
  locale: en_US
  type: website
  img: headshots/mia-smashing.jpg
feed:
  - format: rss
    type: rss+xml
    url: feed.xml
  - format: atom
    type: atom+xml
    url: feed.atom
styles:
  - screen.css
scripts:
  - scripts.js
