url: https://www.miriamsuzanne.com/
source:
  repo: https://github.com/mirisuzanne/mia/
  branch: tree/main/
author: &author Miriam Eric Suzanne
title: *author
description: Art, writing, and code from Miriam Suzanne
email: miriam@miriamsuzanne.com
images: /images/
icon: icons/miriam.svg
nav:
  about: /who/
  rss: /feed.xml
og:
  locale: en_US
  type: website
  img: headshots/mia-smashing.jpg
feed:
  - format: rss
    type: rss+xml
    url: feed.xml
  - format: atom
    type: atom+xml
    url: feed.atom
styles:
  - title: reset
    url: layer-reset.css
    alt: true
  - title: config
    url: layer-config.css
    alt: true
  - title: default
    url: layer-default.css
    alt: true
  - title: all
    url: all.css
scripts:
  - scripts.js
theme:
  light: 'hotpink'
  dark: 'mediumvioletred'
